# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
#     the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

latest_first = 1
latest_second = 2
# result = 0
result = 2

while result <= 4000000:
    new_item = latest_first + latest_second
    if latest_first < latest_second:
        latest_first = new_item
    else:
        latest_second = new_item

    if new_item % 2 == 0:
        result += new_item

print result